# .github/dependabot.yml: Automates dependency updates.
---
version: 2
updates:
  # Docker dependencies for the devcontainer
  - package-ecosystem: "docker"
    directory: "/.devcontainer"
    schedule:
      interval: "monthly"
    reviewers:
      - "Jekwwer"
    assignees:
      - "Jekwwer"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 5

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: ".github"
    schedule:
      interval: "monthly"
    reviewers:
      - "Jekwwer"
    assignees:
      - "Jekwwer"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 5

  # Maven dependencies
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      maven-packages:
        patterns:
          - "org.apache.maven.plugins:*"
    reviewers:
      - "Jekwwer"
    assignees:
      - "Jekwwer"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 5
