# .github/workflows/test.yaml: Runs tests.
---
name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up Java 21
        uses: actions/setup-java@v4.5.0
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Cache Maven packages
        uses: actions/cache@v4.2.0
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up Maven
        run: mvn --version

      - name: Install dependencies
        run: mvn clean install

      - name: Run tests
        run: mvn test
